CREATE TABLE VISITES_LIBRES
(   NO_INSCRIPTION TEXT(14),
SEQ SMALLINT,
DATE_DEBUT TEXT(10),
DATE_FIN TEXT(10),
HEURE_DEBUT TEXT(5),
HEURE_FIN TEXT(5),
COMMENTAIRES_F TEXT(60),
COMMENTAIRES_A TEXT(60)

)