<?php

return [
    'adminEmail' => 'admin@example.com',
    'uploadsPath' => dirname(__DIR__) . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR,
    'zip_list' => dirname(__DIR__) . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'zip_list.txt',
    'ftp_host' => 'ftp.juliehamel.com',
    'ftp_login' => 'centris@juliehamel.com',
    'ftp_pass' => 'R3RK*w2f!87c',
    'upload_zip' => dirname(__DIR__) . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'zip_files' . DIRECTORY_SEPARATOR,
    'upload_unpack' => dirname(__DIR__) . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'unpack_files' . DIRECTORY_SEPARATOR,
    'list_tables' => [
        'ADDENDA',
        'BUREAUX',
        'CARACTERISTIQUES',
        'DEPENSES',
        'ESPACES_REVENUS',
        'FIRMES',
        'GENRES_PROPRIETES',
        'INSCRIPTIONS',
        'LOGEMENTS',
        'MEMBRES',
        'MUNICIPALITES',
        'PHOTOS',
        'PIECES',
        'QUARTIERS',
        'REGIONS',
        'REMARQUES',
        'RENOVATIONS',
        'SOUS_TYPE_CARACTERISTIQUES',
        'TYPE_CARACTERISTIQUES',
        'TYPES_BANNIERES',
        'VALEURS_FIXES'
    ],
];
